samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pqioT01_3_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/ptma03_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pqioT02_5_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/palb03_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/ptmd01_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/ptma04_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/ptma02_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/ptmd03_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/prot261A_13_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/ptmd05_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pade63_7_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pade01_21_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pdav425_21_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/ptma05_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/prot083A_4_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pbal01_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pade311_9_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pade55_8_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/ptri02_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/prot123_19_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pade320_18_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/ptma01_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pdav167_9_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/prot177_18_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pdav56_7_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/palb02_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/palb05_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pdav221_10_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/ptmd02_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/palb01_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pbal02_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/ptmd04_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pqioT02_2_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/prot87_14_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/pdav302_11_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/ptri01_RG_rmdup.bam
samtools index /media/uni/data/projects/Populus_phylogenomic/05.remove_duplicate/01.remove_duplicate_file/palb04_RG_rmdup.bam
