/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/pade.psmc pade.psmcfa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-1.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-2.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-3.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-4.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-5.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-6.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-7.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-8.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-9.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-10.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-11.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-12.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-13.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-14.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-15.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-16.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-17.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-18.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-19.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-20.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-21.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-22.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-23.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-24.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-25.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-26.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-27.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-28.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-29.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-30.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-31.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-32.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-33.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-34.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-35.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-36.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-37.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-38.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-39.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-40.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-41.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-42.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-43.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-44.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-45.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-46.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-47.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-48.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-49.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-50.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-51.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-52.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-53.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-54.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-55.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-56.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-57.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-58.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-59.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-60.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-61.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-62.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-63.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-64.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-65.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-66.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-67.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-68.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-69.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-70.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-71.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-72.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-73.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-74.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-75.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-76.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-77.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-78.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-79.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-80.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-81.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-82.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-83.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-84.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-85.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-86.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-87.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-88.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-89.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-90.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-91.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-92.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-93.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-94.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-95.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-96.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-97.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-98.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-99.psmc pade.split.fa
/home/uni/programme/psmc/psmc-0.6.5/psmc -N25 -t15 -r5 -b -p "4+25*2+4+6" -o /media/uni/data/projects/Populus_phylogenomic/07.snp_structure_analysis/09.psmc/real_psmc/pade/round-100.psmc pade.split.fa
