/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_0 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_0.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 1 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_1 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_1.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 2 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_2 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_2.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 3 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_3 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_3.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 4 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_4 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_4.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 5 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_5 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_5.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 6 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_6 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_6.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 7 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_7 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_7.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 8 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_8 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_8.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 9 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_9 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_9.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 10 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_10 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_10.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 11 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_11 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_11.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 12 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_12 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_12.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 13 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_13 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_13.log
/home/uni/programme/treemix/treemix-1.12/src/treemix -i /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/treemix2.gz -m 14 -root ptri -o /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_14 > /media/uni/data/projects/Populus_phylogenomic/08.all_site_ML_tree/04.treemix/02.without_prot8714/output_files/out_14.log
